version: '3.8'

services:
  # 1. Baza danych PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supertajnehaslo123
      POSTGRES_DB: apartamentydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://admin:supertajnehaslo123@db:5432/apartamentydb?schema=public
      - JWT_SECRET=${JWT_SECRET:-super-secret-key-12345}
      - PORT=3000  
      - NODE_ENV=production
      # Tu wpisałem nową domenę frontendu (ni1b...) dla CORS
      - FRONTEND_URL=http://ni1b367d4m65frdl5c81447i.51.83.197.19.sslip.io
    ports:
      - "3000"
    depends_on:
      - db
    restart: unless-stopped

  # 3. Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Przekazujemy nową domenę backendu do budowania Vite
        - VITE_API_URL=http://swbf3xc5rvmxn5h0x8wmodxe.51.83.197.19.sslip.io
    environment:
      - VITE_API_URL=http://swbf3xc5rvmxn5h0x8wmodxe.51.83.197.19.sslip.io
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
